spring:
  profiles:
    active: -dev
---
spring:
  profiles:
    application:
      name: application-config-bw-dev.properties
---
spring:
  profiles:
    application:
      name: application-config-bw-test.properties